### ISSUE TITLE
VisualRust.Shared is missing from installation package

### ISSUE THREAD

**Issue by LordJZ** [PistonDevelopers/VisualRust#103]
The generated installation package VisualRust.msi is missing VisualRust.Shared.dll that is required for VisualRust.Build.dll to run. This results in this exception during build:

```
------ Build started: Project: RustApplication2, Configuration: Debug AnyCPU ------
C:\Program Files (x86)\MSBuild\VisualRust\VisualRust.Rust.targets(19,5): error : Could not load file or assembly 'VisualRust.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=401f5d177ee7d4a2' or one of its dependencies. The system cannot find the file specified.
   at VisualRust.Build.Rustc.ExecuteInner()
   at VisualRust.Build.Rustc.Execute()
Done building project "RustApplication2.rsproj" -- FAILED.
```

VIsualRust build used:
https://ci.appveyor.com/project/vosen/visualrust/build/job/ubhcib4nvxt95i72/artifacts

Building VisualRust.Shared manually and additing to `C:\Program Files (x86)\MSBuild\VisualRust\` helps.

**Comment by vosen** [comment]
Thanks, it should be fixed now
