### ISSUE TITLE
Add debugging support

### ISSUE THREAD

**Issue by cmr** [PistonDevelopers/VisualRust#13]
This is of course predicated on rustc emitting debuginfo (pdb?) that Visual Studio can understand, but there's nothing nicer than Visual Studio's debugger.

**Comment by vosen** [comment]
Looks like Microsoft will be doing our work for us:
http://blogs.msdn.com/b/vcblog/archive/2015/04/29/open-sourcing-visual-studio-s-gdb-lldb-debug-engine.aspx

**Comment by excaliburHisSheath** [comment]
As of the 1.2 release the other day the 1.3 beta and 1.4 nightly have support for the msvc toolchain which emits a pdb. I've tested my project and I'm able to debug my project with VS.

**Comment by sunsided** [comment]
The MSVC ABI version of Rust for Windows indeed creates PDB files on build, however debugging doesn't seem to work with Visual Rust when F5-ing; breakpoints are ignored.

**Comment by Nuclearfossil** [comment]
New Rust coder and experiencing the same as @sunsided points out.

Visual Studio 2015, using a simple 'hello world' project.

**Comment by vosen** [comment]
With #199 debugging under MSVC ABI (both 32 and 64 bit) should work now.

**Comment by iliekturtles** [comment]
I'm using the latest AppVeyor build based off #200 and Rust stable 1.5 x86_64-pc-windows-msvc. The call stack and break points work (they worked in the November build as well) however watch windows don't work for variables. I'm using the Rust code below modified from the application template and compiling/running in debug mode and get `identifier "xxx_this_is_my_symbol_xxx" is undefined` in the watch window. Am I doing something wrong?

```rust
    let mut xxx_this_is_my_symbol_xxx = 5;
    println!("Hello, world! {}", xxx_this_is_my_symbol_xxx);
    xxx_this_is_my_symbol_xxx += 1;
    println!("Hello, world! {}", xxx_this_is_my_symbol_xxx);
```

**Comment by retep998** [comment]
Rust MSVC debug info is currently lacking due to LLVM being kinda awful at it still. It doesn't know how to emit debug info for local variables yet. You're not doing anything wrong, and there's not much Rust or VisualRust can do here other than wait for LLVM to get their act together.
