### ISSUE TITLE
Support Visual Studio 2015

### ISSUE THREAD

**Issue by Mr-Byte** [PistonDevelopers/VisualRust#135]
With the Visual Studio 2015 RC being released recently and the pending release of VS2015, it would be nice to have 2015 support.

**Comment by ninjabear** [comment]
+1

**Comment by sidewinder** [comment]
+1

**Comment by dogfuntom** [comment]
+1

**Comment by Mr-Byte** [comment]
Doing so,e research, the RC of the 2015 SDK is available at https://www.microsoft.com/en-us/download/details.aspx?id=46850

I may look into what it would take to get a functioning 2015 build beside the 2013 build, to have something ready for the full release of 2015.

**Comment by viperscape** [comment]
:+1:

**Comment by pravic** [comment]
+1

**Comment by fuchsnj** [comment]
+1

**Comment by dummer** [comment]
:+1:

**Comment by cmr** [comment]
Look, just adding +1's clutters up the thread and adds absolutely no value. It's a desirable feature. Lots of people want it for obvious reasons. You don't need to chime in.

**Comment by ninjabear** [comment]
![watch out](http://www.quickmeme.com/img/3c/3c09d14adcdd6626599b630020298af374a0fd836295a829a62c17c45770fd64.jpg)

**Comment by retep998** [comment]
@cmr :+1: on your comment regarding the +1's.

**Comment by vosen** [comment]
This should be fixed by #138

**Comment by dogfuntom** [comment]
Please don't forget to update/add the extension at the Visual Studio Gallery.

**Comment by vosen** [comment]
Yes, I'm just waiting to resolution of a problem with AppVeyor

**Comment by vosen** [comment]
Once we get few small things done (debug settings, etc.). I'll put 0.1.1 with 2015 support. meanwhile VS 2015 support is available in CI builds.
