### ISSUE TITLE
Autocomplete behaviour

### ISSUE THREAD

**Issue by razvan-panda** [PistonDevelopers/VisualRust#136]
When typing `std::` no autocomplete is being shown until pressing at least 1 valid first character of the autocomplete list. It would be useful to be able to see the entire autocomplete list when typing something like `std::` without being forced to filter on at least 1st character.

**Comment by andersforsgren** [comment]
I believe this is how racer (the autocomplete program) works. I'll investigate if it's actually a feature request in racer. If so, I'll raise it there: https://github.com/phildawes/racer

**Comment by vosen** [comment]
I think it's not the racer fault but the way we do things.
I've seen this before and racer seemed to generate right completions but our code was confused about something, definitely needs investigating

**Comment by andersforsgren** [comment]
This might be true, I just never managed to get it to accept a non-prefixed completion, but at that time the completion was sketchy at best and often returning no completions even for valid prefixes on windows (issues with line breaks etc). The situation should be much better with a stable Rust and a much improved racer, so this is well worth revisiting. I'll investigate.

**Comment by andersforsgren** [comment]
Oh, I misunderstood that I think, completing on "std::" vs. completely prefix free completion, I.e ctrl+space on a blank line to show variables and methods in scope like for C#. The latter I think is not possible in racer but the former should definitely be.

**Comment by vosen** [comment]
Should be closed by #137
