### ISSUE TITLE
Improve vs2015 debugger user-experience

### ISSUE THREAD

**Issue by vosen** [PistonDevelopers/VisualRust#149]
As of #145, we've now got 2015 debug support. There are still some ways to make it nicer for general consumption.
- [x] Check $PATH$ for gdb.exe presence (and show in the settings if it can't be found)
- [ ] ~~Don't launch debugger at all if no gdb found~~
- [ ] ~~Gray-out plugin-wide debugging settings (Tools/Options/...) with a short message how you can get it working (vs2015 + C++ mobile tools)~~
- [ ] Inject Rust installation path to `%PATH%` when launching the debugger

In the future we might want to bundle gdb.exe.

**Comment by vadimcn** [comment]
Not sure about #3: the ability to specify command line args and working directory is still useful.  Besides, in VS2013 we support launching under the built-in debugger.

**Comment by vosen** [comment]
I meant plugin-wide options in Tools/Options settings (edited first post to clarify).
I didn't specifically check for it, but currently, builtin debugger give us support for debugging dynamically-linked C++ libraries, right?
I'm mostly worried about the most common use case, which is running pure Rust code. In this case launching with builtin debugger will just produce "You don't have any debug symbols for this executable, do you want to continue?" message box every time. This is very confusing for the end user, especially, if he has debug symbols in the project enabled.

**Comment by vadimcn** [comment]
That's true, although I personally would prefer *some* debugger vs no debugger at all.  There's also cv2pdb...
Btw, do you already have a fix for the 'path containing spaces' issue?

**Comment by vosen** [comment]
Well, yeah, there's cv2pdb, but I think it's better to just wait for Microsoft to open-source their gdb support and use it in 0.2 (or 0.3) for both vs2013 and vs2015 and in 0.1.1 just have no debugging (unless you have vs2015 + C++ Mobile plugin).
As for paths, yes, quoting with `"` works. I just forgot to merge it yesterday. Done it now in #150.

**Comment by retep998** [comment]
The GDB engine for Visual Studio is now open source.
http://blogs.msdn.com/b/vcblog/archive/2015/07/20/source-now-available-for-gdb-lldb-debug-engine.aspx

**Comment by vosen** [comment]
I've just tried ripping off MIEngine and shipping it with Visual Rust works OK (modulo some changes). I'll upload the repos tomorrow.

**Comment by vosen** [comment]
Closed by #177
