### ISSUE TITLE
can't find crate for `glutin_window`

### ISSUE THREAD

**Issue by ctaggart** [PistonDevelopers/VisualRust#162]
I got Visual Rust build #80 from AppVeyor, Rust 1.1, and Visual Studio 2015 installed. I created a fork of `rocket` and added the a .rsproj file and .sln. 

https://github.com/ctaggart/rocket

Unfortunately, I'm getting this error and I don't understand why. `cargo build` works just fine.

![image](https://cloud.githubusercontent.com/assets/80104/8818459/8c464544-2ff6-11e5-82eb-941ab48e094b.png)

/cc @aochagavia

**Comment by aochagavia** [comment]
I have no idea about this :wink: ... Never used VisualRust

**Comment by Boddlnagg** [comment]
Currently there is no cargo support in VisualRust yet (see #3). When you try to build, it will just call `rustc`, which doesn't know abou the dependencies. Until carge integration is implemented, you can have a look at [this page](https://github.com/brakmic/IHaveNoClue), the section "Using VS External Tools" describes how to manually set up VS to invoke cargo.

**Comment by gerwin3** [comment]
I found you can build the library separately and get the .rlib in the target/debug and all .rlib files in target/debug/deps and copy them to "C:\Program Files\Rust stable 1.1\bin\rustlib\i686-pc-windows-gnu\lib". It's ugly but works!

(I also tried adding AdditionalLibPaths="$(ProjectDir)" to the Rust.target file in MSBuild/VisualRust. If it worked, the rlibs could go in the project directory making things a bit cleaner. But it doens't work for some reason...)

**Comment by verysimplenick** [comment]
Finnaly I create VisualRust.Build.Cargo.dll and VisualRust.Build.Cargo.target. It's simple works fine for me.

**Comment by Boddlnagg** [comment]
Fixed by #234
