### ISSUE TITLE
Visual Rust extension not found in Visual Studio 2015 "Extensions and Updates" search

### ISSUE THREAD

**Issue by briansmith** [PistonDevelopers/VisualRust#166]
I tried "Rust" and "Visual Rust" but I got zero results for both.

**Comment by razvan-panda** [comment]
:+1:

**Comment by RichiCoder1** [comment]
:+1: Just went to install rust and ran into this.

**Comment by vosen** [comment]
Done

**Comment by razvan-panda** [comment]
@vosen Thank you so much for this! :+1: 

Being able to use breakpoints for debugging and change the runtime state using the immediate window or watch variables is awesome.

**Comment by razvan-panda** [comment]
Wow, even drag and dropping the next instruction pointer works the same way it works in C#. This is really really useful.

**Comment by vosen** [comment]
All the thanks should go to Microsoft's [MIEngine](https://github.com/Microsoft/MIEngine) team. We are just repackaging their work.

**Comment by razvan-panda** [comment]
@vosen Thanks to the MIEngine team too, in any case, very nice integration!

Are there are any plans to make a list of features of Visual Rust and add them to the README.md? Seeing something like:

* debugger powered by MIEngine
* watch window
* immediate window (for contextual REPL experience)
* using both the watch and the immediate window the runtime state can be changed
* ability to drag and drop to change the next code line that will be executed
* call stack view and navigation

Would be quite convincing that this is a great plugin.
