### ISSUE TITLE
build #87, could not load PistonDevelopers.MIDebugEngine

### ISSUE THREAD

**Issue by ctaggart** [PistonDevelopers/VisualRust#167]
![image](https://cloud.githubusercontent.com/assets/80104/9023569/a24dbb8a-3855-11e5-932c-6a05b6c25699.png)

I am running Visual Studio 2015 on Windows 10. I installed build #87, the latest on AppVeyor. https://ci.appveyor.com/project/vosen/visualrust/history

I'm at Rust Camp right now and I was hoping to demo it. I had an earlier version working on another computer.

**Comment by vosen** [comment]
Should be fixed by #168, build 88 should be OK

**Comment by ctaggart** [comment]
Cool! I'll give it a shot.

**Comment by ctaggart** [comment]
It works! =)

![image](https://cloud.githubusercontent.com/assets/80104/9023832/1560463a-3863-11e5-9434-610b8eb57013.png)
