### ISSUE TITLE
Visual Rust breaks Visual Studio when editing .rs files not in a Visual Rust project

### ISSUE THREAD

**Issue by briansmith** [PistonDevelopers/VisualRust#181]
1. Install Visual Rust.
2. Open a solution with (only) C++ projects in Visual Studio.
3. Open a .rs file while that C++ solution is open.
4. Try to edit the .rs file.

I consistently get a "serviceProvider" message box popping up when I try to edit the .rs file or even when I use the arrow keys to navigate. Sometimes opening a .rs file will prevent Visual Studio from even being able to shut down normally (I have to kill it from the Task Manager). I also sometimes get an "an exception has occurred" dialog box in these situatoins.

I believe Visual Rust is making assumptions about a Visual Rust project being loaded that aren't valid. I frequently edit .rs files in C++ projects so this affects me a lot.

**Comment by vosen** [comment]
Closed by #189
