### ISSUE TITLE
Couldn't build "Debug" configuration in VS 2015

### ISSUE THREAD

**Issue by yacoder** [PistonDevelopers/VisualRust#185]
Building in "Debug" configuration returns 1519 errors on my machine using VS 2015, and this was the default build configuration when I opened the solution. Switching to "Debug-CI" or "Release" fixes the errors. We should maybe remove the "Debug" configuration? Or merge it with "Debug-CI"?

**Comment by vosen** [comment]
Paste the error log somewhere (gist or pastebin). `Debug` configuration is pretty much identical to `Release`, `Debug-CI` is a special configuration for AppVeyor.

**Comment by yacoder** [comment]
Hmm... couldn't repro today... will keep an eye on it  :-)
