### ISSUE TITLE
Visual Studio Community 2015 crashes

### ISSUE THREAD

**Issue by bennyn** [PistonDevelopers/VisualRust#190]
Hi,

I installed the VisualRust extension for my Visual Studio Community 2015 Edition on Windows 10. I am just learning the Rust programming language so I wrote this little program:

```rust
use std::io;

fn main() {
    let mut stdin = io::stdin();
    let input = &mut String::new();
	
    loop {
        input.clear();
        stdin.read_line(input);
        println!("{}", input);
    }
}
```

I can start that program with Visual Studio but as soon as I close it, Visual Studio crashes. Is this something related to VisualRust or has it to do with Visual Studio in general?

**Comment by yacoder** [comment]
VisualRust receives exit code "030000000472", which doesn't fit into UInt32, and crashes. It's a weird exit code, but really there's no need to crash the IDE... :-)

**Comment by bennyn** [comment]
Thanks for the quick response! Nice to see that my first steps in Rust turn into something useful. 

Looking forward to the fix! :smiley:

**Comment by buybackoff** [comment]
+1, have the same issue with the latest stable release (using exactly the same snippet found on SO). Is AppVeyor build already updated for this?

**Comment by yacoder** [comment]
Sorry, this is not yet fixed in VisualRust. The problem seems to be in the original Microsoft/MIEngine code used by VisualRust to interact with VS. I'll try to open a pull request there soon...

**Comment by vosen** [comment]
Merged now. [AppVeyor build 106](https://ci.appveyor.com/project/vosen/visualrust/build/106) has the fix.
