### ISSUE TITLE
VisualRust doesn't find Rust installation if installed via Multirust

### ISSUE THREAD

**Issue by Lisoph** [PistonDevelopers/VisualRust#198]
VisualRust doesn't find the Rust installation, if Rust was installed with Diggsey's Multirust.

![multirust](https://cloud.githubusercontent.com/assets/3426722/11163324/ee8af3d8-8aca-11e5-803d-cc66f00aef4a.PNG)

**Comment by vosen** [comment]
Closed by #200

**Comment by Lisoph** [comment]
Nice, great work!
