### ISSUE TITLE
Trying to run project from VS2015 throws an INVALIDARGS error and aborts

### ISSUE THREAD

**Issue by detuur** [PistonDevelopers/VisualRust#205]
I have just installed the Rust toolchain (GNU version).

Steps to reproduce:
* Create new "Rust Application" project
* Press F5 to start debugging

It throws up the following error:
> The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

Running it without debugging does not cause any problem.

**Comment by detuur** [comment]
#202 appears to be a duplicate, noticed just now

**Comment by vosen** [comment]
Fixed by #208
