### ISSUE TITLE
Target Visual Studio 2012

### ISSUE THREAD

**Issue by vosen** [PistonDevelopers/VisualRust#21]
We are currently building only for VS2013, it should be a matter of changing definitions in .vsixmanifest and actually testing generated .vsix. Since both 2012 and 2013 version targets .Net 4.5 it won't affect the code.

**Comment by kvark** [comment]
This would be very handy to have.

**Comment by Boddlnagg** [comment]
This is not possible with the new project system. Closing as wontfix.
