### ISSUE TITLE
Not clear how to add libraries to a project (if it is even possible!)

### ISSUE THREAD

**Issue by Timmmm** [PistonDevelopers/VisualRust#212]
Maybe I'm missing something very obvious, but it doesn't seem like there is any way to add an external library to Visual Rust projects. It doesn't use Cargo (yet) so that method is out, importing the source directly doesn't work because then `use libraryname` doesn't work. I assumed I would have had to manually put the source somewhere and use "add existing items" but that doesn't really work either. It gives errors about rust files already existing - do I want to overwrite them?

Anyway, either it isn't possible, or there's no way to know how to do it.

**Comment by Boddlnagg** [comment]
It's currently not possible, until Cargo integration is done. See #194.
