### ISSUE TITLE
Is debugging supported?

### ISSUE THREAD

**Issue by pravic** [PistonDevelopers/VisualRust#213]
I am sorry, but is VisualRust is working at all?
#### Project support

When project was created, you cannot remove its default directory (src) and files (lib.rs for example). Also you cannot move project file outside of its directory - it creates src and src/lib.rs again.
#### Autocomplete

It shows only keywords. Always. That's all.
#### Go to definition

F12? Nothing was happened.
#### MIEngine-powered debugging featuring
- [x] Call stack view and navigation

Thats all.
- [ ] Conditional breakpoints
- [ ] Watch window (with the ability to change the runtime state)
- [ ] Immediate window (with the ability to change the runtime state)

All what I can see is [identifier is undefined](http://c2n.me/3vXgqP5.png).

```
rustc -vV
rustc 1.9.0-nightly (21922e1f4 2016-03-21)
binary: rustc
commit-hash: 21922e1f48b263b39498cfeec79c1ca3f5886efe
commit-date: 2016-03-21
host: i686-pc-windows-msvc
release: 1.9.0-nightly
```

May be I need rustc with GNU ABI?

**Comment by MihaMarkic** [comment]
Briefly looking at it. Seems like F12 works, autocomplete shows function names as well but not (primitive) types, conditional breakpoints work, watch windows works and immediate window as well.

**Comment by MaulingMonkey** [comment]
Conditional breakpoints, the watch window, and the immediate window seem to all work for me as of f005c247f0f30aa0d84fab655d192743de53bba8 with the following rustup stable provided binaries:

```
rustc 1.18.0 (03fc9d622 2017-06-06)
cargo 0.19.0 (28d1d60d4 2017-05-16)
```

This can probably be closed?
