### ISSUE TITLE
Build is always 'up-to-date' (MSVC)

### ISSUE THREAD

**Issue by jcdickinson** [PistonDevelopers/VisualRust#214]
# Environment
- Visual Studio 2015 Community Update 1
- Rust 1.7 MSVC
- VisualRust 0.1.2
# Repro
1. Create a new project
2. Run the project. **Outcome:** `Hello World!`
3. Add the following to `main`: `println!("Test");`
4. Optional: save `main.rs`.
5. Run the project. **Outcome:** `Hello World!` **Expected:** `Hello World!<newline>Test`.
6. Right click on the project and select `Rebuild`.
7. Run the project. **Outcome:** as expected.
# Summary

The build is not detecting changes to files.
# Remarks

An older version of Visual Rust (and Rust) was installed on the environment, but _uninstalled_ prior to installing these latest versions.

[MSBuild log](https://github.com/PistonDevelopers/VisualRust/files/191747/build.txt)

**Comment by fluffels** [comment]
This affects me too.

**Comment by DanTup** [comment]
Seeing same here. I installed 1.9 from the rust site, then installed the Visual Rust extension. I don't believe I've ever had any older versions installed.

The first time it did ask me "Do you want to rebuild before running?". I thought that was a rather stupid question and ticked "Don't show me again" and then the "Yes" button. Maybe it interpreted that as "Yes this time, but never ask me again and assume no in future". I can't find any settings to change this or reset it so I get the dialog again.

**Comment by rpjohnst** [comment]
@DanTup The option you're looking for is under Tools > Options > Projects and Solutions > Build and Run, labeled "On Run, when projects are out of date:". Checking "Don't show me again" and clicking "Yes" sets that option to "Always build", and setting it to "Prompt to build" gives you back the prompt.

The behavior here sounds like it's set to "Never build," but the MSBuild log here makes it seem like it is trying to build but the actual build process is getting skipped somehow.

**Comment by DanTup** [comment]
@rpjohnst that was the first place I checked and it's say to `Prompt`, but it does not :( I figured the dialog I saw was maybe Visual Rust specific and not the standard VS one (I'd never seen look like it did here before).

**Comment by fluffels** [comment]
@rpjohnst Mine is set to "Always Build"

**Comment by josephg** [comment]
I'm running into this problem too, on a fresh install of everything 👀

**Comment by TurkeyMan** [comment]
Fresh install. This is broken.
This is surely the very first feature that must work? There is nothing more critical than this...

**Comment by Boddlnagg** [comment]
This is going to be fixed with #234. You can try to build that branch yourself ...

**Comment by Boddlnagg** [comment]
This should no longer appear with #234 ... can you confirm that?

**Comment by TurkeyMan** [comment]
Is there CI output? Nightly builds or something?

**Comment by Boddlnagg** [comment]
Yes. The debug build (with the tests) is currently not working (see #238), but the Release configuration builds and produces an MSI as an artifact: https://ci.appveyor.com/project/vosen/visualrust

**Comment by quixoticaxis** [comment]
Installed .msi from your link. Now the build is no longer up-to-date. So it seems it is fixed.
Can't check this in full right now, because of the older cargo.exe on my machine which I can't currently re-install.

**Comment by jcdickinson** [comment]
Checked with MSVC build (1.13.0) and this works perfectly.
