### ISSUE TITLE
Build is always 'up-to-date' (GNU)

### ISSUE THREAD

**Issue by jcdickinson** [PistonDevelopers/VisualRust#215]
# Environment

_GNU-specific duplicate of #214. Pull requesting incoming._
- Visual Studio 2015 Community Update 1
- Rust 1.7 GNU
- VisualRust 0.1.2
# Repro
1. Create a new project
2. Run the project. **Outcome:** `Hello World!`
3. Add the following to `main`: `println!("Test");`
4. Optional: save `main.rs`.
5. Run the project. **Outcome:** `Hello World!` **Expected:** `Hello World!<newline>Test`.
6. Right click on the project and select `Rebuild`.
7. Run the project. **Outcome:** as expected.
# Summary

The build is not detecting changes to files.
# Remarks

An older version of Visual Rust (and Rust) was installed on the environment, but _uninstalled_ prior to installing these latest versions.

**Comment by Boddlnagg** [comment]
This should no longer appear with #234 ... can you confirm that?

**Comment by jcdickinson** [comment]
This is working perfectly.
