### ISSUE TITLE
Consider moving to VS Common Project System

### ISSUE THREAD

**Issue by Boddlnagg** [PistonDevelopers/VisualRust#223]
This seems to be the future. See https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/intro.md, especially the section _Is CPS right for me?_

[R Tools for VS](https://github.com/Microsoft/RTVS) seems to be using this, as a reference.

**Comment by Boddlnagg** [comment]
In the long term we should also probably move to a folder-based project approach, where you can open any folder that contains a `Cargo.toml`: https://blogs.msdn.microsoft.com/visualstudio/2016/04/12/open-any-folder-with-visual-studio-15-preview/

This probably implies moving away from an MSBuild task for compiling, but I'm not sure.

**Comment by Boddlnagg** [comment]
The folder-based approach only works natively in VS "15" (currently in preview), but I've got a prototypical implementation of something similar working for VS2015 using CPS, based on code from [R Tools](https://github.com/Microsoft/RTVS). This does not imply moving away from an MSBuild task (however, we should define a new one that relies on `cargo` instead of `rustc` directly), but it *does* imply dropping support for everything pre-VS2015 ... currently we also support VS2013.

**Comment by Vbif** [comment]
Cargo support is really important, definitely more important than VS2013 support

**Comment by Boddlnagg** [comment]
Cargo support is not directly blocked by this (i.e. one could implement Cargo support with the current project system), but I think any new feature, including Cargo support, will be a lot easier to implement based on CPS, and also a lot more maintainable. And CPS is becoming even more powerful (and probably also better documented) in VS "15", since Microsoft is migrating the [C# and VB project systems to CPS](https://github.com/dotnet/roslyn-project-system).

So my conclusion is that we should drop VS2013 support.
