### ISSUE TITLE
Syntax highlighting doesn't work in the "Dark" environment in Visual Studio Pro 2013 Update 5. 

### ISSUE THREAD

**Issue by mjfmechanic** [PistonDevelopers/VisualRust#226]
I've attempted to change the font colors under the options, however, they do not change under the current "Dark" IDE environment. I was able to change the highlighting of the line numbers etc but that is a general IDE function rather than a Rust specific function. If you have any suggestions please post! Thanks!

Mike

**Comment by MaulingMonkey** [comment]
Working in master / latest appveyor build - although we've ditched VS2013 support, so this is against VS2015.
