### ISSUE TITLE
Project properties display issues

### ISSUE THREAD

**Issue by Thomas-Fleming** [PistonDevelopers/VisualRust#228]
I'm experiencing a few display issues with the project properties.

Where: `Build -> Platform target:`
Issue: Combo-box isn't wide enough to read "x86_64-pc-windows-gnu"

Where: `Build -> Optimization level:`
Issue: Combo-box isn't wide enough to read any of the options.

Where: `Debug`
Issue: The whole screen is messed up. The text boxes extend beyond the right of my screen and there is no horizontal scroll bar. The vertical spacing between options is far too large. I can't input anything for "Start action:".

It's worth noting that my laptop has a QHD screen which might be affecting the layout.

**Comment by Boddlnagg** [comment]
This dialog has been removed with the switch made in #234, so this issue is no longer relevant.
