### ISSUE TITLE
System.IO.Abstractions not deployed in MSI

### ISSUE THREAD

**Issue by wildcatgerry** [PistonDevelopers/VisualRust#235]
Build 137 
Commit 17d0eace
Artifact taken from AppVeyor Release

After successful installation, adding a new rust project to a solution throws an exception
Could not load file or assembly'System.IO.Abstractions' Version=2.0.0.124

Seems like the library is missing from the WiX project files.

**Comment by Boddlnagg** [comment]
Thanks for the report! I already noticed that this assembly is referenced, but neither installed nor used. In #234 I have removed the reference, so it will no longer be required.

**Comment by Boddlnagg** [comment]
@wildcatgerry Can you try the latest build artifact from AppVeyor?

**Comment by wildcatgerry** [comment]
Thanks. Closing.
