### ISSUE TITLE
Can't goto error

### ISSUE THREAD

**Issue by TurkeyMan** [PistonDevelopers/VisualRust#236]
Errors are presented like this:

```
  --> src\emulator\parts\processor.rs:25:38
```

VS doesn't understand that format, and you can't dbl-click to go to the error... pipe through sed?

**Comment by Boddlnagg** [comment]
The currently released version of VisualRust is not yet compatible with the new error format. You have to build it yourself. We have fixed this by using JSON output (#230), but that fix has not made it into a release. Until the next release (which will hopefully also inculde #234), you have to build VisualRust yourself.

**Comment by Boddlnagg** [comment]
Can you confirm that this is fixed in the latest AppVeyor Release artifact (https://ci.appveyor.com/project/vosen/visualrust)?

**Comment by MaulingMonkey** [comment]
Working for me in master.
