### ISSUE TITLE
Add option to read sources from `rustc --print sysroot`

### ISSUE THREAD

**Issue by Boddlnagg** [PistonDevelopers/VisualRust#239]
Standard library sources can now be installed via rustup and are available at the location shown by `rustc --print sysroot`. We should add an option to the Visual Rust general options page to automatically use this path (and maybe even make it the default).

**Comment by Vbif** [comment]
I have made some work [here](https://github.com/Vbif/VisualRust/tree/sysroot_for_rust_src). The main problem is: which rustc run to get sysroot? Maybe we need first aggregate ToolVersion and TargetTriple to "toolchain" class. And make toolchain option for project or solution.

**Comment by Boddlnagg** [comment]
The `Cargo` wrapper returned by `Cargo.FindSupportedInstallation()` already has a `RustcExecutable` property for this purpose. But there already is a `GetSysrootAsync` method [here](https://github.com/PistonDevelopers/VisualRust/blob/e984dfebd4a8136b83d4dcc241011579102e7042/VisualRust.Shared/Cargo.cs#L64-L68), which you can probably use. In a later step, we should centralize access to the toolchain, i.e. there should be only a single instance of the `Cargo` wrapper which handles the currently selected toolchain (related to #242). Toolchain selection will probably be delegated to `rustup`.

**Comment by Vbif** [comment]
https://github.com/PistonDevelopers/VisualRust/pull/251
