### ISSUE TITLE
.rs file extension is interpreted as "Rust Project" in Windows Explorer

### ISSUE THREAD

**Issue by quixoticaxis** [PistonDevelopers/VisualRust#253]
It seems that Visual Rust installation marks both ".rsproj" and ".rs" as "Rust Project" extensions. It's nothing serious but it would be prettier to have 2 labels: "Rust Project" for ".rsproj" and something like "Rust Source File" for ".rs".

**Comment by quixoticaxis** [comment]
I have installed Visual Rust from Extensions Gallery and I guess file associations are created by .msi so it probably can be fixed easily.

**Comment by CountOmega** [comment]
with vr in vs 2017 .rs is shown as a .rs file.

**Comment by quixoticaxis** [comment]
Glad to know, thank you.
