### ISSUE TITLE
Can't load .rsproj

### ISSUE THREAD

**Issue by vosen** [PistonDevelopers/VisualRust#255]
While loading Cargo.toml nicely creates corresponding .rsproj, the project file doesn't load and there's no option for .rsproj in project open dialog.
Something must have went wrong when moving to CPS and most likely pkgdef is broken in some subtle way.

**Comment by Boddlnagg** [comment]
This is probably solvable by modifying the [ProvideCpsProjectFactoryAttribute](https://github.com/PistonDevelopers/VisualRust/blob/master/VisualRust.ProjectSystem.FileSystemMirroring/Package/Registration/ProvideCpsProjectFactoryAttribute.cs)
