### ISSUE TITLE
Get rid of BOM in templates (if possible)

### ISSUE THREAD

**Issue by Boddlnagg** [PistonDevelopers/VisualRust#259]
Currently the .rs and Cargo.toml files in the templates use a BOM to make VS use UTF-8 encoding. Using a BOM is generally discouraged, and I would like to get rid of it, but VS must still use UTF-8 for these files.

**Comment by briansmith** [comment]
I believe the extension "just" needs to make sure every *.rs file's encoding is set to UTF-8 in the pre-save event. There's an extension that already does this in a more general sense at https://vlasovstudio.com/fix-file-encoding/, so it definitely seems possible.

Note in particular that UTF-8 is the only legal encoding of Rust source files, according to the Rust reference, so there's no need to have any fancy configuration options or anything to control this.

**Comment by Boddlnagg** [comment]
I think this was fixed by #260.
