### ISSUE TITLE
Question: Do we have cargo support ?

### ISSUE THREAD

**Issue by sherry-ummen** [PistonDevelopers/VisualRust#261]
Hello,

I trying out the version from here https://marketplace.visualstudio.com/items?itemName=vosen.VisualRust

Wanted to know does this support cargo project structure?

2nd Question. I get this error when compiling the Visual rust code
![image](https://cloud.githubusercontent.com/assets/2572380/20553900/c1603eaa-b160-11e6-81d4-4a22c6497042.png)

Any help on how to resolve this? I am on master branch

**Comment by Boddlnagg** [comment]
About the first question: No, the version of VisualRust currently available at the marketplace does not yet support Cargo.

Second quesiton: I've never seen this error. Is Java installed on your system? Antlr requires it.

**Comment by sherry-ummen** [comment]
Thanks I forgot to reopen visual studio after reopening it that error went but I have now build failure

![image](https://cloud.githubusercontent.com/assets/2572380/20557454/49c076bc-b174-11e6-9470-a9cac06cd102.png)

**Comment by Boddlnagg** [comment]
That `Phx.FatalError` looks like it's coming from FxCop (http://stackoverflow.com/questions/30490358/error-in-fxcop-phoenix-analysis-engine). Do you have a special configuration there? I've never seen an error like this.

**Comment by sherry-ummen** [comment]
Nice! That fixed it. Thanks for your help.
