### ISSUE TITLE
Support for Visual Studio 2017

### ISSUE THREAD

**Issue by RReverser** [PistonDevelopers/VisualRust#271]
VS 2017 allows much more fine-grained installation, and even though it's currently in RC stage, already enjoying it much more than 2015 version.

One thing I'm missing is though that VisualRust doesn't detect or doesn't offer installation for this version of Visual Studio yet.

**Comment by KodrAus** [comment]
VS 2017 is officially [a thing](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes). It'd be great to support it! I'm not familiar with what's changed from an extension writer's point of view though.

**Comment by RReverser** [comment]
Me neither, although extensions from the store (Extensions and Updates) which I used in VS2015 seem to work just fine. Might be a matter of just updating VisualRust's installer to detect VS2017 as well.

**Comment by gurry** [comment]
VS 2017 [allows you to open a folder](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/open-any-folder-with-c-sources-in-visual-studio-2017-rc/) instead of having to create a project. This is great for those who prefer the native folder structure created by Cargo to a VS project. If Visual Rust can support this folder-only approach it'll be fantastic.

**Comment by elahn** [comment]
Looks like [most of the work has been done](https://github.com/PistonDevelopers/VisualRust/commit/34076bfc1a2e249ec2dc14ddb0c9a80292879ba3) and [various issues fixed](https://github.com/PistonDevelopers/VisualRust/commit/5bfa2e21fcc50c2c2f5584058e0872c9b02be14d), but the [build is failing on AppVeyor](https://ci.appveyor.com/project/vosen/visualrust/history). Building it locally is now on my todo list. Thanks for all your work on this @vosen! 😍

**Comment by MaulingMonkey** [comment]
Build is succeeding on AppVeyor now.  Huzzah!
