### ISSUE TITLE
Add a project system

### ISSUE THREAD

**Issue by cmr** [PistonDevelopers/VisualRust#4]
- [x] Recognize rust projects
- [X] Add project template for application (equivalent to `cargo new`)
- [x] Add project template for binary (equivalent to `cargo new --bin`)
- [ ] Add project template for creating projects from existing codebase
- [x] Add support for adding .rs items to projects
- [x] Support build/rebuild/clean
- [x] Get rid of "Add references"
- [x] Add property pages
- [x] Force proper project structure

**Comment by vosen** [comment]
Project system is pretty much ready for 0.1.
One thing that won't make a cut is creating projects from existing codebase, as it's not very useful without cargo support. I split it to #119.
