### ISSUE TITLE
The Rust project templates don't show up in VS 2013

### ISSUE THREAD

**Issue by fubar-coder** [PistonDevelopers/VisualRust#90]
I already tried to [Flush the Visual Studio Template Cache](https://danielsaidi.wordpress.com/2011/01/14/flush-the-visual-studio-template-cache/), but it didn't work. Maybe it's a problem that I have a VS2013 with german language pack?

EDIT: I also used [this](https://ci.appveyor.com/project/vosen/visualrust/build/job/1wexalgtt6bl2gym/artifacts) installer.

**Comment by vosen** [comment]
Looks like I'm an ugly anglophile and VIsualRust have been installing templates with en-us locale.
Can you please give me confirmation for this bug? Go to `<PATH_TO_VS_2013_INSTALL>\Common7\IDE\ProjectTemplates\Rust\1033` (`<PATH_TO_VS_2013_INSTALL>` is usually `C:\Program Files (x86)\Microsoft Visual Studio 12.0`) it should contain `ApplicationProject.zip` and `LibraryProject.zip`. Now move those two zip files one level up (to `<PATH_TO_VS_2013_INSTALL>\Common7\IDE\ProjectTemplates\Rust`). You should now see Rust category and two project templates in the create new project window.

**Comment by vosen** [comment]
And flush template cache after moving those two files

**Comment by fubar-coder** [comment]
Thank you, the project templates are now showing up.

**Comment by vosen** [comment]
Thanks, I'll have this fixed later today.
In the meantime you should do the same about item template (move content of `<PATH_TO_VS_2013_INSTALL>\Common7\IDE\ItemTemplates\Rust\1033` one level up).
